### ISSUE TITLE
No options in panel.

### ISSUE THREAD

**Issue by SplitMilky** [ahgsql/StyleSelectorXL#2]
There is nothing to chose from for styles in the drop down panel.

![image](https://github.com/ahgsql/StyleSelectorXL/assets/81430176/8b7868c9-eda3-421e-9a74-8b03e8fefffd)

**Comment by SplitMilky** [comment]
I refreshed the page but I actually had to hit the Reload UI at the bottom of the window for everything to show up properly.

**Comment by ahgsql** [comment]
Yeah, actullay its always better to Restart UI Instead of Reloading it
